import React, { useState } from 'react';
import Head from 'next/head';

import { loadSideBarPosts, loadTagPosts } from '../api/posts';
import { Footer, Header, Section } from '@/components';
import ModalMenu from '@/components/ModalMenu';
import Tags from '@/components/Tags';
import logo from '@/assets/images/logo.jpeg';

const LOAD_MORE_STEP = 4;
export default function Interviews({ initialPosts, total, tag, sideBarPosts }) {
  const [posts, setPosts] = useState(initialPosts);
  const [totalPosts, setTotalPosts] = useState(total);
  const [modalVisible, setModalVisible] = useState(false);
  const [visiblePopularsPosts, setVisiblePopularsPosts] = useState(true);
  const [visibleSearchResult, setVisibleSearchResult] = useState(false);

  return (
    <Section>
      <Head>
        <title>{`Posts by tag - ${tag}`}</title>
        {/*<meta name="description" content="Generated by create next app" />*/}
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />

        <meta property="og:image" content={logo.src} />
        <meta name="twitter:image" content={logo.src} />
      </Head>
      <ModalMenu setModalVisible={setModalVisible} modalVisible={modalVisible} />
      <Header
        setPosts={setPosts}
        setTotalPosts={setTotalPosts}
        setModalVisible={setModalVisible}
        setVisiblePopularsPosts={setVisiblePopularsPosts}
        setVisibleSearchResult={setVisibleSearchResult}
        tag={tag}
      />
      <Tags
        posts={posts}
        setPosts={setPosts}
        total={totalPosts}
        tag={tag}
        visibleSearchResult={visibleSearchResult}
        sideBarPosts={sideBarPosts}
      />
      <Footer subscribe={false} />
    </Section>
  );
}

export const getServerSideProps = async ({ query }) => {
  const { posts } = await loadTagPosts(query.tag);
  const { sideBarPosts } = await loadSideBarPosts();

  return {
    props: {
      initialPosts: posts,
      tag: query.tag,
      sideBarPosts,
    },
  };
};
