import Head from 'next/head';
import {Footer, Header, Section} from "@/components";

export default function Home({ posts }) {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <Header />
        <Section>
          Posts
        </Section>
        <Section>
          <Footer />
        </Section>
      </main>
    </>
  );
}

export const getServerSideProps = async () => {

}
